### ISSUE TITLE
Support tsconfig paths

### ISSUE THREAD

**Issue by prescottprue** [bennycode/ts2esm#89]
Huge thanks for the lib - it has saved countless hours

When a path alias is used via `paths` setting in tsconfig it seems that ts2esm is not converting the import to have `.js` suffix

It would be awesome if we could check tsconfig (and even an extends file if one exists - i.e. tsconfig.paths.json referenced in "extends" setting of tsconfig) for `paths` settings - if they are found, make sure to apply suffix to imports using those aliases

Example

**tsconfig.json**

```json
{
  "compilerOptions": {
    "paths": {
      "@libs/*": ["src/libs/*"]
    }
  }
}
```

Would convert the following import:

```ts
import { someLib } from '@libs/some-lib'
```
to

```ts
import { someLib } from '@libs/some-lib.js'`
```

Preferably also handling if the import is pointing to a folder that contains an `index.js` as is currently handled for import conversions

**Comment by bennycode** [comment]
Hi @prescottprue, I happy to hear that you find my tool valuable. 🙂

I actually implemented support for `paths` in #53. Is your case specifically about the `index.js` file which isn't taken care of? I can try to reproduce this or do you have an open source repository that I can use for testing? 

I also haven't tested TS configs that extend TS configs. I was hoping that https://github.com/dsherret/ts-morph handles this for me under the hood when calling `project.getCompilerOptions().paths`. Let me double check...

**Comment by bennycode** [comment]
Hey @prescottprue, I just tested a few cases...

## Simple Export

**src/libs/some-lib.ts**

```ts
export const someLib = {};
```

**src/main.ts**

Before:

```ts
import { someLib } from '@libs/some-lib';
console.log(someLib);
```

After running `tsesm`:

```ts
import { someLib } from '@libs/some-lib.js';

console.log(someLib);
```

👍 - Test Passed

## Index Export


**src/libs/some-lib/index.ts**

```ts
export const someLib = {};
```

**src/main.ts**

Before:

```ts
import { someLib } from '@libs/some-lib';
console.log(someLib);
```

After running `tsesm`:

```ts
import { someLib } from '@libs/some-lib/index.js';

console.log(someLib);
```

👍  - Test Passed

An import just from `@libs/some-lib` wouldn't work:

![image](https://github.com/user-attachments/assets/bedec6c4-f4d5-419f-bd02-bba9a484b1cf)

**Comment by prescottprue** [comment]
Thanks for the quick response and testing!

Maybe I am doing something wrong then?

Here is a zip of the repro:

[test-ts2esm.zip](https://github.com/user-attachments/files/17513087/test-ts2esm.zip)


Currently I have been doing the transform via `yarn dlx src/**` - it shows that the src/index.jts is being processed, but the alias is not transformed

**Comment by prescottprue** [comment]
Oh awesome, glad to hear! In meantime I'll see if doing that in the existing projects I'm converting fixes it

**Comment by bennycode** [comment]
Hey @prescottprue, I just released a new minor version. Can you please try again using **ts2esm v2.2.0**?

I've also created a snapshot test for your use case. While doing so, I [noticed a bug](https://github.com/vitest-dev/vscode/issues/512) in the [VS Code extension for Vitest](https://marketplace.visualstudio.com/items?itemName=vitest.explorer).

It's always fun to see how everything connects and how software improves with each use case. 🙂

**Comment by prescottprue** [comment]
Amazing thanks! Oh nice - wasn't aware of that extension for Vitest, I'll for sure start using that. Totally agree on the on improving with each use case and that only happens by OSS maintainers spending the time to checkout issues and replicate exactly like you did - bravo 👏 

From the looks of it in my test repo I uploaded in the zip above, I'm still not seeing `@libs/some-lib` being switched to `@libs/some-lib/index.js` in index.ts with 2.2.0. I'll keep poking at it though and see if it is something on my end

**Comment by bennycode** [comment]
Hi @prescottprue, I just published a lot of improvements with ts2esm v2.2.4 - Can you please run it with the `--debug` option and tell me if it properly adjusted your imports? 🙂
